# Generated by Django 5.2 on 2025-04-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasemana',
            options={'verbose_name': 'Día de la Semana', 'verbose_name_plural': 'Días de la Semana'},
        ),
        migrations.AlterModelOptions(
            name='horariotutoria',
            options={'ordering': ['dia', 'hora_inicio'], 'verbose_name': 'Horario de Tutoría', 'verbose_name_plural': 'Horarios de Tutorías'},
        ),
        migrations.AddField(
            model_name='horariotutoria',
            name='materia',
            field=models.CharField(default='Sin materia', max_length=100),
        ),
        migrations.AddField(
            model_name='horariotutoria',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas (Opcional)'),
        ),
        migrations.AddField(
            model_name='horariotutoria',
            name='paralelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Paralelo'),
        ),
    ]
