# Generated by Django 5.2 on 2025-04-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_horariotutoria_url_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotutoria',
            name='ruta_local',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta Local'),
        ),
    ]
